import { Compliance, EntitySetupGuide } from './types';

export const INDIAN_STATES = [
  'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chhattisgarh', 'Goa', 'Gujarat', 'Haryana', 
  'Himachal Pradesh', 'Jharkhand', 'Karnataka', 'Kerala', 'Madhya Pradesh', 'Maharashtra', 'Manipur', 
  'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha', 'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu', 
  'Telangana', 'Tripura', 'Uttar Pradesh', 'Uttarakhand', 'West Bengal', 'Delhi'
];

export const ENTITY_SETUP_GUIDES: Record<string, EntitySetupGuide> = {
  'Pvt Ltd': {
    entityType: 'Pvt Ltd',
    pros: ['Limited Liability', 'Separate Legal Entity', 'High Credibility for Funding', 'Perpetual Succession'],
    cons: ['High Compliance Cost', 'Strict Audit Requirements', 'Difficult to Close'],
    steps: [
      { title: 'Digital Signature (DSC)', description: 'Obtain DSC for all proposed directors.', timeline: '1-2 Days', cost: '₹1,000 - ₹2,000' },
      { title: 'Name Approval (RUN)', description: 'Reserve a unique name via MCA portal.', timeline: '2-3 Days', cost: '₹1,000' },
      { title: 'SPICe+ Filing', description: 'Main incorporation form (MoA, AoA, PAN, TAN).', timeline: '5-7 Days', cost: '₹6,000 - ₹15,000' },
      { title: 'Bank Account', description: 'Open a current account using the Certificate of Incorporation.', timeline: '2-4 Days', cost: 'Varies' }
    ]
  },
  'LLP': {
    entityType: 'LLP',
    pros: ['Limited Liability', 'Lower Compliance than Pvt Ltd', 'No Dividend Distribution Tax', 'Flexible Management'],
    cons: ['Difficult to raise VC funding', 'FDI restrictions in some sectors', 'Strict penalties for late filing'],
    steps: [
      { title: 'DSC & DPIN', description: 'Obtain DSC and DPIN for designated partners.', timeline: '2 Days', cost: '₹2,000' },
      { title: 'Name Reservation (FiLLiP)', description: 'Apply for name approval via MCA.', timeline: '3 Days', cost: '₹200' },
      { title: 'Incorporation Filing', description: 'Submit FiLLiP form with partner details.', timeline: '7 Days', cost: '₹3,000 - ₹7,000' },
      { title: 'LLP Agreement', description: 'Draft and file the agreement within 30 days of incorporation.', timeline: '30 Days', cost: '₹2,000 + Stamp Duty' }
    ]
  },
  'OPC': {
    entityType: 'OPC',
    pros: ['Single Owner Control', 'Limited Liability', 'Separate Legal Entity', 'Less Compliance than Pvt Ltd'],
    cons: ['Cannot scale to multiple owners easily', 'Turnover limits for conversion', 'Single person risk'],
    steps: [
      { title: 'DSC & DIN', description: 'Obtain DSC and DIN for the sole director.', timeline: '2 Days', cost: '₹1,500' },
      { title: 'Name Approval', description: 'Reserve name via RUN service.', timeline: '2 Days', cost: '₹1,000' },
      { title: 'Incorporation Filing', description: 'Submit SPICe+ with Nominee details.', timeline: '5 Days', cost: '₹5,000 - ₹10,000' }
    ]
  },
  'Proprietorship': {
    entityType: 'Proprietorship',
    pros: ['Easiest to Start', 'Minimal Compliance', 'Total Control', 'Low Cost'],
    cons: ['Unlimited Personal Liability', 'Difficult to raise capital', 'No separate legal identity'],
    steps: [
      { title: 'PAN Card', description: 'Use personal PAN of the owner.', timeline: 'Instant', cost: '₹0' },
      { title: 'Shop & Establishment', description: 'Register under state labor laws.', timeline: '3-5 Days', cost: '₹500 - ₹2,000' },
      { title: 'GST Registration', description: 'Mandatory if turnover > ₹20L/40L.', timeline: '7 Days', cost: '₹0 (Govt fee)' }
    ]
  },
  'Partnership': {
    entityType: 'Partnership',
    pros: ['Easy to Form', 'Shared Responsibility', 'Minimal Compliance', 'Low Setup Cost'],
    cons: ['Unlimited Liability for Partners', 'Potential for Conflict', 'Dissolution on death/exit'],
    steps: [
      { title: 'Partnership Deed', description: 'Draft and notarize the agreement.', timeline: '2 Days', cost: '₹1,000 + Stamp Duty' },
      { title: 'PAN & TAN', description: 'Apply for entity-specific tax IDs.', timeline: '5 Days', cost: '₹200' },
      { title: 'Registration (Optional)', description: 'Register with Registrar of Firms for legal standing.', timeline: '15 Days', cost: '₹1,000' }
    ]
  }
};

export const INPUT_HELP_TEXT: Record<string, string> = {
  isIncorporated: "Determines if you need a setup guide (pre-incorporation) or a compliance roadmap (post-incorporation).",
  entityType: "Different entities (Pvt Ltd, LLP, etc.) have vastly different annual filing requirements under the Companies Act.",
  state: "Professional Tax (PT) and Labour Welfare Fund (LWF) are state-specific. Some states have higher compliance overhead than others.",
  turnover: "Key thresholds like ₹20L/40L (GST), ₹50L/1Cr (Tax Audit), and ₹5Cr (E-invoicing) are triggered by annual revenue.",
  businessModel: "GST registration thresholds differ for Goods (₹40L) and Services (₹20L).",
  entityAge: "New companies (< 1 year) have critical one-time filings like INC-20A and Auditor appointment.",
  headcount: "Triggers labor laws: ESI (10+), POSH (10+), EPF (20+), and Payment of Bonus Act (20+).",
  paidUpCapital: "Affects stamp duty, ROC fees, and triggers Secretarial Audit if capital exceeds ₹50Cr.",
  industry: "Sector-specific licenses like RBI (Fintech), FSSAI (Food), or BIS (Manufacturing) are determined by your industry.",
  subIndustry: "Granular sub-sectors (e.g., Payments vs Lending) have different regulatory oversight (NIC codes).",
  foreignInvestment: "Triggers FEMA/RBI compliances like FC-GPR and FLA returns. Also requires IEC for cross-border trade.",
  msmeVendors: "Triggers MSME Form 1 (Half-yearly) if you have outstanding dues exceeding 45 days to MSME vendors.",
  dataProcessing: "Triggers Privacy Policy, Terms of Service, and DPDP Act compliance for handling personal user data.",
  hasBorrowings: "Triggers Vigil Mechanism (> ₹50Cr) and Internal Audit (> ₹100Cr) requirements.",
  isDPIITRecognized: "If not recognized, we show the 'Incentive' card to help you unlock tax and IP benefits.",
  interstateSales: "Mandatory GST registration is required for any inter-state supply, regardless of turnover.",
  isEcommerce: "E-commerce sellers must register for GST and comply with TCS (Tax Collected at Source) rules.",
  hasContractLabor: "Triggers CLRA (Contract Labour Regulation & Abolition) registration if you engage third-party labor.",
  hasForeignLoans: "Triggers ECB (External Commercial Borrowing) reporting via Form ECB-2 to the RBI."
};
export const INDUSTRIES = {
  'Fintech': ['Payments', 'Lending', 'Wealthtech', 'Insurance'],
  'Healthtech': ['Telemedicine', 'Pharmacy', 'Medical Devices'],
  'Edtech': ['Online Learning', 'Certification'],
  'E-commerce': ['Marketplace', 'Inventory-led'],
  'Food & Agri': ['Food Processing', 'Organic', 'Export'],
  'Logistics': ['Last-mile', 'Warehousing', 'Freight'],
  'SaaS/IT': ['Data Analytics', 'Cybersecurity', 'Enterprise Software'],
  'Manufacturing': ['Electronics', 'Textiles', 'Chemicals'],
  'Other': ['General']
};

export const COMPLIANCE_MASTER: Compliance[] = [
  // --- SECTOR SPECIFIC (NIC/INDUSTRY) ---
  {
    id: 'rbi-pa-license',
    category: 'Fintech',
    name: 'RBI Payment Aggregator (PA) License',
    urgency: 'Red',
    what: 'Mandatory license for entities facilitating payments between merchants and customers.',
    when: 'Before starting payment aggregation services.',
    where: 'RBI Portal',
    whereUrl: 'https://www.rbi.org.in/',
    how: 'Apply with net worth proof (₹15Cr initially, ₹25Cr later) and tech audit.',
    penalty: 'Cease operations + Heavy fines.',
    isMandatory: true,
    trigger: (inputs) => inputs.industry === 'Fintech' && inputs.subIndustry === 'Payments',
  },
  {
    id: 'nbfc-registration',
    category: 'Fintech',
    name: 'NBFC Registration (CoR)',
    urgency: 'Red',
    what: 'Certificate of Registration for non-banking financial companies.',
    when: 'Before starting lending or financial activities.',
    where: 'RBI Portal',
    whereUrl: 'https://www.rbi.org.in/',
    how: 'Apply with min NOF of ₹10Cr and clean track record.',
    penalty: 'Imprisonment + Fine.',
    isMandatory: true,
    trigger: (inputs) => inputs.industry === 'Fintech' && inputs.subIndustry === 'Lending',
  },
  {
    id: 'telemedicine-guidelines',
    category: 'Healthtech',
    name: 'Telemedicine Practice Guidelines',
    urgency: 'Yellow',
    what: 'Compliance with MCI/NMC guidelines for online medical consultations.',
    when: 'Ongoing for any telemedicine platform.',
    where: 'NMC Portal',
    whereUrl: 'https://www.nmc.org.in/',
    how: 'Ensure RMPs are registered, maintain patient records, and follow data privacy.',
    penalty: 'License cancellation for doctors + Legal action against platform.',
    isMandatory: true,
    trigger: (inputs) => inputs.industry === 'Healthtech' && inputs.subIndustry === 'Telemedicine',
  },
  {
    id: 'e-pharmacy-license',
    category: 'Healthtech',
    name: 'E-Pharmacy License (Draft Rules)',
    urgency: 'Red',
    what: 'Registration for selling medicines online.',
    when: 'Before starting online pharmacy operations.',
    where: 'CDSCO / State Drug Controller',
    whereUrl: 'https://cdsco.gov.in/',
    how: 'Apply for retail/wholesale drug license and follow e-pharmacy draft rules.',
    penalty: 'Seizure of stock + Closure of business.',
    isMandatory: true,
    trigger: (inputs) => inputs.industry === 'Healthtech' && inputs.subIndustry === 'Pharmacy',
  },
  {
    id: 'fssai-central-license',
    category: 'Food & Agri',
    name: 'FSSAI Central License',
    urgency: 'Red',
    what: 'Mandatory license for large-scale food businesses or exporters.',
    when: 'Before starting operations if turnover > ₹20Cr.',
    where: 'FoSCoS Portal',
    whereUrl: 'https://foscos.fssai.gov.in/',
    how: 'Apply online with detailed project plan and safety certificates.',
    penalty: 'Up to ₹5 Lakh fine + Imprisonment.',
    isMandatory: true,
    trigger: (inputs) => inputs.industry === 'Food & Agri' && inputs.turnover === '> ₹100Cr',
  },
  {
    id: 'bis-certification',
    category: 'Manufacturing',
    name: 'BIS Certification (ISI Mark)',
    urgency: 'Red',
    what: 'Mandatory quality certification for specific products (electronics, toys, etc.).',
    when: 'Before selling products in the Indian market.',
    where: 'Bureau of Indian Standards',
    whereUrl: 'https://www.bis.gov.in/',
    how: 'Apply for product testing and factory inspection.',
    penalty: 'Confiscation of goods + Fine.',
    isMandatory: true,
    trigger: (inputs) => inputs.industry === 'Manufacturing' && inputs.subIndustry === 'Electronics',
  },
  {
    id: 'e-waste-authorization',
    category: 'Manufacturing',
    name: 'E-Waste EPR Authorization',
    urgency: 'Red',
    what: 'Extended Producer Responsibility for managing electronic waste.',
    when: 'Before manufacturing or importing electronic goods.',
    where: 'CPCB Portal',
    whereUrl: 'https://eprewastecpcb.nic.in/',
    how: 'Apply for EPR authorization with a waste collection plan.',
    penalty: 'Environmental compensation + License suspension.',
    isMandatory: true,
    trigger: (inputs) => inputs.industry === 'Manufacturing' && inputs.subIndustry === 'Electronics',
  },
  {
    id: 'pan-tan',
    category: 'Foundation',
    name: 'PAN & TAN Registration',
    urgency: 'Red',
    what: 'Permanent Account Number and Tax Deduction Account Number.',
    when: 'Immediately upon incorporation.',
    where: 'Income Tax Portal / NSDL',
    whereUrl: 'https://www.onlineservices.nsdl.com/',
    how: 'Usually part of SPICe+; if not, file Form 49A and 49B.',
    penalty: '₹10,000 for non-possession.',
    isMandatory: true,
    trigger: (inputs) => true,
  },
  {
    id: 'inc-20a',
    category: 'MCA',
    name: 'Commencement of Business (INC-20A)',
    urgency: 'Red',
    what: 'Mandatory declaration that every company must file before starting business operations.',
    when: 'Within 180 days of incorporation.',
    where: 'MCA V3 Portal',
    whereUrl: 'https://www.mca.gov.in/',
    how: 'File Form INC-20A with a CA-certified bank statement showing subscription money.',
    penalty: '₹50,000 for company + ₹1,000/day for directors.',
    isMandatory: true,
    trigger: (inputs) => ['Pvt Ltd', 'OPC'].includes(inputs.entityType) && inputs.entityAge === '< 1 year',
  },
  {
    id: 'adt-1',
    category: 'MCA',
    name: 'Appointment of First Auditor',
    urgency: 'Red',
    what: 'Notice to the Registrar about the appointment of the first statutory auditor.',
    when: 'Within 30 days of incorporation.',
    where: 'MCA V3 Portal',
    whereUrl: 'https://www.mca.gov.in/',
    how: 'File Form ADT-1 with the auditor\'s consent letter and board resolution.',
    penalty: '₹100 per day + potential disqualification of directors.',
    isMandatory: true,
    trigger: (inputs) => ['Pvt Ltd', 'OPC'].includes(inputs.entityType) && inputs.entityAge === '< 1 year',
  },

  // --- MCA PILLAR (ANNUAL MANDATORY) ---
  {
    id: 'dir-3-kyc',
    category: 'MCA',
    name: 'Director KYC (DIR-3 KYC)',
    urgency: 'Green',
    what: 'Annual KYC for every individual who holds a DIN.',
    when: 'Annually by September 30th.',
    where: 'MCA V3 Portal',
    whereUrl: 'https://www.mca.gov.in/',
    how: 'Submit DIR-3 KYC (Web) if details are unchanged.',
    penalty: '₹5,000 flat fine + DIN deactivation.',
    isMandatory: true,
    trigger: (inputs) => ['Pvt Ltd', 'LLP', 'OPC'].includes(inputs.entityType),
  },
  {
    id: 'mgt-7',
    category: 'MCA',
    name: 'Annual Return (MGT-7/7A)',
    urgency: 'Green',
    what: 'Detailed return containing information about shareholders and directors.',
    when: 'Within 60 days of AGM.',
    where: 'MCA V3 Portal',
    whereUrl: 'https://www.mca.gov.in/',
    how: 'Prepare list of shareholders, transfers, and meetings; file via Form MGT-7.',
    penalty: '₹100 per day of delay.',
    isMandatory: true,
    trigger: (inputs) => ['Pvt Ltd', 'OPC'].includes(inputs.entityType),
  },
  {
    id: 'aoc-4',
    category: 'MCA',
    name: 'Financial Statement Filing (AOC-4)',
    urgency: 'Green',
    what: 'Filing of annual financial statements with the Registrar of Companies.',
    when: 'Within 30 days of the Annual General Meeting (AGM).',
    where: 'MCA V3 Portal',
    whereUrl: 'https://www.mca.gov.in/',
    how: 'Prepare Balance Sheet, P&L, and Auditor Report; file via Form AOC-4.',
    penalty: '₹100 per day of delay.',
    isMandatory: true,
    trigger: (inputs) => ['Pvt Ltd', 'OPC'].includes(inputs.entityType),
  },
  {
    id: 'llp-form-8',
    category: 'MCA',
    name: 'Statement of Account & Solvency (Form 8)',
    urgency: 'Yellow',
    what: 'Annual filing for LLPs declaring financial status and solvency.',
    when: 'By October 30th annually.',
    where: 'MCA V3 Portal',
    whereUrl: 'https://www.mca.gov.in/',
    how: 'Prepare financial statements and file Form 8 signed by partners.',
    penalty: '₹100 per day (no upper limit).',
    isMandatory: true,
    trigger: (inputs) => inputs.entityType === 'LLP',
  },
  {
    id: 'llp-form-11',
    category: 'MCA',
    name: 'Annual Return for LLP (Form 11)',
    urgency: 'Yellow',
    what: 'Summary of partners and contributions of the LLP.',
    when: 'By May 30th annually.',
    where: 'MCA V3 Portal',
    whereUrl: 'https://www.mca.gov.in/',
    how: 'File Form 11 with details of partners and their contributions.',
    penalty: '₹100 per day.',
    isMandatory: true,
    trigger: (inputs) => inputs.entityType === 'LLP',
  },
  {
    id: 'llp-form-3',
    category: 'MCA',
    name: 'LLP Agreement (Form 3)',
    urgency: 'Red',
    what: 'Filing the initial LLP agreement or any subsequent changes.',
    when: 'Within 30 days of incorporation or change.',
    where: 'MCA V3 Portal',
    whereUrl: 'https://www.mca.gov.in/',
    how: 'Execute agreement on stamp paper and file Form 3.',
    penalty: '₹100 per day (no upper limit).',
    isMandatory: true,
    trigger: (inputs) => inputs.entityType === 'LLP' && inputs.entityAge === '< 1 year',
  },
  {
    id: 'partnership-deed-reg',
    category: 'MCA',
    name: 'Partnership Deed Registration',
    urgency: 'Yellow',
    what: 'Registration of the partnership deed with the Registrar of Firms (ROF).',
    when: 'Optional but recommended; required for legal standing.',
    where: 'Registrar of Firms (State)',
    whereUrl: 'https://rof.maharashtra.gov.in/',
    how: 'Submit deed, Form A, and fees to the ROF.',
    penalty: 'Cannot sue third parties or partners without registration.',
    isMandatory: false,
    trigger: (inputs) => inputs.entityType === 'Partnership',
  },
  {
    id: 'dpt-3',
    category: 'MCA',
    name: 'Return of Deposits (DPT-3)',
    urgency: 'Yellow',
    what: 'Annual return to report outstanding receipts of money or loan by a company.',
    when: 'By June 30th every year.',
    where: 'MCA V3 Portal',
    whereUrl: 'https://www.mca.gov.in/',
    how: 'File Form DPT-3 with auditor\'s certificate if reporting deposits.',
    penalty: '₹5,000 to ₹25,000 + interest on deposits.',
    isMandatory: true,
    trigger: (inputs) => ['Pvt Ltd', 'OPC'].includes(inputs.entityType),
  },
  {
    id: 'msme-1',
    category: 'MCA',
    name: 'MSME Form 1 (Half-Yearly)',
    urgency: 'Yellow',
    what: 'Reporting of outstanding dues to MSME vendors exceeding 45 days.',
    when: 'Half-yearly (Oct 31 for Apr-Sep, Apr 30 for Oct-Mar).',
    where: 'MCA V3 Portal',
    whereUrl: 'https://www.mca.gov.in/',
    how: 'File MSME Form 1 with details of vendors and reasons for delay.',
    penalty: '₹20,000 for company + ₹1,000/day for officers.',
    isMandatory: true,
    trigger: (inputs) => inputs.msmeVendors === true && ['Pvt Ltd', 'OPC'].includes(inputs.entityType),
  },
  {
    id: 'ben-2',
    category: 'MCA',
    name: 'SBO Declaration (BEN-2)',
    urgency: 'Red',
    what: 'Reporting of Significant Beneficial Owners to the Registrar.',
    when: 'Within 30 days of receiving BEN-1 from owners.',
    where: 'MCA V3 Portal',
    whereUrl: 'https://www.mca.gov.in/',
    how: 'File Form BEN-2 with details of individuals holding >10% stake indirectly.',
    penalty: '₹1 Lakh + ₹1,000/day.',
    isMandatory: true,
    trigger: (inputs) => ['Pvt Ltd', 'OPC'].includes(inputs.entityType),
  },
  {
    id: 'board-meetings',
    category: 'MCA',
    name: 'Board Meetings (Min. 4)',
    urgency: 'Green',
    what: 'Mandatory meetings of the Board of Directors to discuss company affairs.',
    when: 'At least 4 meetings a year, with gap < 120 days.',
    where: 'Internal Records / Minutes Book',
    whereUrl: 'https://www.mca.gov.in/',
    how: 'Issue notice, hold meeting, and record minutes in the Minutes Book.',
    penalty: '₹25,000 for company + ₹5,000 for every officer.',
    isMandatory: true,
    trigger: (inputs) => ['Pvt Ltd', 'OPC'].includes(inputs.entityType),
  },
  {
    id: 'agm-holding',
    category: 'MCA',
    name: 'Annual General Meeting (AGM)',
    urgency: 'Green',
    what: 'Mandatory annual meeting of shareholders to approve financials and appoint auditors.',
    when: 'Within 6 months of the end of the financial year (by Sep 30th).',
    where: 'Registered Office / Online',
    whereUrl: 'https://www.mca.gov.in/',
    how: 'Issue 21-day notice, hold meeting, and pass resolutions.',
    penalty: '₹1,00,000 + ₹5,000 per day of delay.',
    isMandatory: true,
    trigger: (inputs) => ['Pvt Ltd', 'OPC'].includes(inputs.entityType),
  },
  {
    id: 'pas-3',
    category: 'MCA',
    name: 'Return of Allotment (PAS-3)',
    urgency: 'Red',
    what: 'Reporting the allotment of shares to the Registrar of Companies.',
    when: 'Within 30 days of allotment of shares.',
    where: 'MCA V3 Portal',
    whereUrl: 'https://www.mca.gov.in/',
    how: 'File Form PAS-3 with the list of allottees and board resolution.',
    penalty: '₹1,000 per day (up to ₹1 Lakh).',
    isMandatory: true,
    trigger: (inputs) => inputs.foreignInvestment === true, // Investment implies allotment
  },
  {
    id: 'dir-8-mbp-1',
    category: 'MCA',
    name: 'Director Disclosures (DIR-8 & MBP-1)',
    urgency: 'Green',
    what: 'Annual disclosure by directors of their interest in other entities and non-disqualification.',
    when: 'First board meeting of every financial year.',
    where: 'Internal Records / Minutes Book',
    whereUrl: 'https://www.mca.gov.in/',
    how: 'Directors submit Form MBP-1 and DIR-8 to the company; recorded in minutes.',
    penalty: '₹50,000 to ₹1,00,000 for the director.',
    isMandatory: true,
    trigger: (inputs) => ['Pvt Ltd', 'OPC'].includes(inputs.entityType),
  },
  {
    id: 'statutory-audit',
    category: 'MCA',
    name: 'Statutory Audit (Process)',
    urgency: 'Red',
    what: 'Mandatory annual audit of financial statements by an independent CA.',
    when: 'Annually, before the AGM (typically by Aug/Sep).',
    where: 'Internal / Auditor Report',
    whereUrl: 'https://www.mca.gov.in/',
    how: 'Prepare books, provide records to CA, and obtain signed Audit Report.',
    penalty: '₹1 Lakh to ₹5 Lakh for the company.',
    isMandatory: true,
    trigger: (inputs) => ['Pvt Ltd', 'OPC'].includes(inputs.entityType),
  },
  {
    id: 'dir-12-filing',
    category: 'MCA',
    name: 'Change in Directors (DIR-12)',
    urgency: 'Conditional',
    what: 'Reporting any appointment, resignation, or change in designation of directors.',
    when: 'Within 30 days of the change.',
    where: 'MCA V3 Portal',
    whereUrl: 'https://www.mca.gov.in/',
    how: 'File Form DIR-12 with the resolution and consent/resignation letter.',
    penalty: '₹100 per day of delay (no upper limit).',
    isMandatory: true,
    trigger: (inputs) => ['Pvt Ltd', 'OPC'].includes(inputs.entityType),
  },
  {
    id: 'mgt-14-filing',
    category: 'MCA',
    name: 'Filing of Resolutions (MGT-14)',
    urgency: 'Conditional',
    what: 'Filing of specific board or shareholder resolutions with the ROC.',
    when: 'Within 30 days of passing the resolution.',
    where: 'MCA V3 Portal',
    whereUrl: 'https://www.mca.gov.in/',
    how: 'File Form MGT-14 with the resolution copy and explanatory statement.',
    penalty: '₹1 Lakh + ₹500 per day of delay.',
    isMandatory: true,
    trigger: (inputs) => ['Pvt Ltd', 'OPC'].includes(inputs.entityType),
  },
  {
    id: 'internal-audit',
    category: 'MCA',
    name: 'Internal Audit (Sec 138)',
    urgency: 'Yellow',
    what: 'Mandatory appointment of an internal auditor to review company controls.',
    when: 'Annually, if turnover > ₹200Cr or borrowings > ₹100Cr.',
    where: 'Internal Records / Board Report',
    whereUrl: 'https://www.mca.gov.in/',
    how: 'Appoint a CA or Cost Accountant as Internal Auditor via Board Resolution.',
    penalty: '₹5,000 to ₹25,000 for every officer in default.',
    isMandatory: true,
    trigger: (inputs) => (inputs.turnover === '> ₹100Cr' || inputs.hasBorrowings) && ['Pvt Ltd', 'OPC'].includes(inputs.entityType),
  },
  {
    id: 'secretarial-audit',
    category: 'MCA',
    name: 'Secretarial Audit (MR-3)',
    urgency: 'Red',
    what: 'Audit of compliance with corporate laws by a Company Secretary.',
    when: 'Annually, if turnover > ₹250Cr or capital > ₹50Cr.',
    where: 'MCA V3 Portal (Attached to AOC-4)',
    whereUrl: 'https://www.mca.gov.in/',
    how: 'Appoint a practicing CS to conduct audit and issue Form MR-3.',
    penalty: '₹1 Lakh to ₹5 Lakh for the company.',
    isMandatory: true,
    trigger: (inputs) => inputs.turnover === '> ₹100Cr',
  },
  {
    id: 'vigil-mechanism',
    category: 'MCA',
    name: 'Vigil Mechanism / Whistleblower Policy',
    urgency: 'Yellow',
    what: 'Establishment of a mechanism for directors/employees to report concerns.',
    when: 'Mandatory if borrowings from banks/FIs > ₹50Cr.',
    where: 'Internal / Website Disclosure',
    whereUrl: 'https://www.mca.gov.in/',
    how: 'Draft policy, appoint a nodal officer, and disclose details in Board Report.',
    penalty: '₹50,000 to ₹2,00,000.',
    isMandatory: true,
    trigger: (inputs) => inputs.hasBorrowings && ['Pvt Ltd', 'OPC'].includes(inputs.entityType),
  },
  {
    id: 'statutory-registers',
    category: 'MCA',
    name: 'Maintenance of Statutory Registers',
    urgency: 'Green',
    what: 'Mandatory maintenance of registers like Register of Members, Directors, Loans, etc.',
    when: 'Ongoing; must be updated within 7-15 days of any change.',
    where: 'Registered Office (Physical or Electronic)',
    whereUrl: 'https://www.mca.gov.in/',
    how: 'Maintain registers in prescribed formats (MGT-1, MBP-2, etc.).',
    penalty: '₹50,000 to ₹3,00,000 for the company.',
    isMandatory: true,
    trigger: (inputs) => ['Pvt Ltd', 'OPC'].includes(inputs.entityType),
  },
  {
    id: 'csr-compliance',
    category: 'MCA',
    name: 'CSR Compliance (Sec 135)',
    urgency: 'Red',
    what: 'Mandatory spending of 2% of average net profits on social responsibility.',
    when: 'Annually, if profit > ₹5Cr, turnover > ₹1000Cr, or net worth > ₹500Cr.',
    where: 'MCA V3 Portal',
    whereUrl: 'https://www.mca.gov.in/',
    how: 'Form a CSR Committee, draft policy, and spend on approved activities.',
    penalty: 'Twice the amount to be transferred or ₹1 Crore (whichever is less).',
    isMandatory: true,
    trigger: (inputs) => ['₹5Cr - ₹100Cr', '> ₹100Cr'].includes(inputs.turnover),
  },

  // --- TAXATION PILLAR ---
  {
    id: 'itr-filing',
    category: 'Taxation',
    name: 'Income Tax Return (ITR)',
    urgency: 'Green',
    what: 'Annual filing of entity income and tax liability.',
    when: 'By Oct 31st (for Audit cases) or July 31st.',
    where: 'Income Tax Portal',
    whereUrl: 'https://www.incometax.gov.in/',
    how: 'File IR-6 (Companies) or ITR-5 (LLP/Partnership).',
    penalty: '₹5,000 - ₹10,000 late fee + interest.',
    isMandatory: true,
    trigger: (inputs) => true,
  },
  {
    id: 'advance-tax',
    category: 'Taxation',
    name: 'Advance Tax Payments',
    urgency: 'Yellow',
    what: 'Payment of income tax in installments if tax liability > ₹10,000.',
    when: 'Quarterly (June 15, Sep 15, Dec 15, Mar 15).',
    where: 'Income Tax Portal',
    whereUrl: 'https://www.incometax.gov.in/',
    how: 'Calculate estimated profit and pay via Challan 280.',
    penalty: 'Interest under Sec 234B and 234C.',
    isMandatory: true,
    trigger: (inputs) => inputs.turnover !== 'Pre-revenue',
  },
  {
    id: '15ca-15cb',
    category: 'Taxation',
    name: 'Foreign Remittance (15CA/15CB)',
    urgency: 'Conditional',
    what: 'Reporting of payments made to non-residents (e.g., SaaS, AWS, Consultants).',
    when: 'Before making any foreign remittance.',
    where: 'Income Tax Portal',
    whereUrl: 'https://www.incometax.gov.in/',
    how: 'Obtain Form 15CB from a CA and file Form 15CA online.',
    penalty: '₹1 Lakh per default.',
    isMandatory: true,
    trigger: (inputs) => inputs.turnover !== 'Pre-revenue',
  },
  {
    id: 'equalization-levy',
    category: 'Taxation',
    name: 'Equalization Levy (Digital Tax)',
    urgency: 'Yellow',
    what: 'Tax on payments to foreign digital companies (6% for ads, 2% for e-commerce).',
    when: 'Monthly deposit by 7th of next month; Annual return by June 30th.',
    where: 'Income Tax Portal',
    whereUrl: 'https://www.incometax.gov.in/',
    how: 'Deduct levy from payment to foreign entity and deposit via Challan 285.',
    penalty: 'Interest + 100% penalty of the levy amount.',
    isMandatory: true,
    trigger: (inputs) => inputs.turnover !== 'Pre-revenue',
  },
  {
    id: 'gst-reg-mandatory',
    category: 'Taxation',
    name: 'GST Registration (Mandatory)',
    urgency: 'Red',
    what: 'Mandatory indirect tax registration for high-turnover or inter-state entities.',
    when: 'When turnover > ₹40L (Goods) / ₹20L (Services), or Inter-state sales, or E-commerce.',
    where: 'GST Portal',
    whereUrl: 'https://www.gst.gov.in/',
    how: 'Apply online with PAN, Address Proof, and Entity documents.',
    penalty: '10% of tax due or ₹10,000.',
    isMandatory: true,
    trigger: (inputs) => {
      if (inputs.interstateSales || inputs.isEcommerce) return true;
      if (inputs.businessModel === 'Service' || inputs.businessModel === 'Both') {
        return !['Pre-revenue', '< ₹20L'].includes(inputs.turnover);
      }
      // Product only
      return !['Pre-revenue', '< ₹20L', '₹20L - ₹40L'].includes(inputs.turnover);
    },
  },
  {
    id: 'gst-reg-voluntary',
    category: 'Taxation',
    name: 'GST Registration (Voluntary)',
    urgency: 'Incentive',
    what: 'Optional registration to claim Input Tax Credit (ITC) and enable inter-state sales.',
    when: 'Anytime, even with zero turnover.',
    where: 'GST Portal',
    whereUrl: 'https://www.gst.gov.in/',
    how: 'Apply online; requires regular monthly/quarterly filings once registered.',
    penalty: 'N/A (Voluntary), but once registered, filings become mandatory.',
    isMandatory: false,
    trigger: (inputs) => {
      const isMandatory = (inputs.interstateSales || inputs.isEcommerce) ||
        ((inputs.businessModel === 'Service' || inputs.businessModel === 'Both') && !['Pre-revenue', '< ₹20L'].includes(inputs.turnover)) ||
        (inputs.businessModel === 'Product' && !['Pre-revenue', '< ₹20L', '₹20L - ₹40L'].includes(inputs.turnover));
      return !isMandatory;
    },
  },
  {
    id: 'tds-returns',
    category: 'Taxation',
    name: 'Quarterly TDS Returns',
    urgency: 'Yellow',
    what: 'Filing of Tax Deducted at Source for payments like Salary, Rent, Professional Fees.',
    when: 'Quarterly (July 31, Oct 31, Jan 31, May 31).',
    where: 'TRACES Portal',
    whereUrl: 'https://www.tdscpc.gov.in/',
    how: 'Deduct tax, deposit via Challan 281, and file Form 24Q/26Q.',
    penalty: '₹200 per day of delay.',
    isMandatory: true,
    trigger: (inputs) => inputs.headcount > 0 || inputs.turnover !== 'Pre-revenue',
  },
  {
    id: 'income-tax-audit',
    category: 'Taxation',
    name: 'Tax Audit (Sec 44AB)',
    urgency: 'Red',
    what: 'Mandatory audit of accounts by a Chartered Accountant.',
    when: 'By September 30th if turnover > ₹1Cr (Business) / ₹50L (Profession).',
    where: 'Income Tax Portal',
    whereUrl: 'https://www.incometax.gov.in/',
    how: 'Appoint a CA to audit books and file Form 3CD.',
    penalty: '0.5% of turnover or ₹1.5 Lakh (whichever is lower).',
    isMandatory: true,
    trigger: (inputs) => {
      if (inputs.businessModel === 'Service') {
        return !['Pre-revenue', '< ₹20L', '₹20L - ₹40L'].includes(inputs.turnover); // > 40L is close to 50L
      }
      return ['₹5Cr - ₹100Cr', '> ₹100Cr'].includes(inputs.turnover);
    },
  },
  {
    id: 'gst-annual-return',
    category: 'Taxation',
    name: 'GST Annual Return (GSTR-9)',
    urgency: 'Green',
    what: 'Consolidated annual return of all monthly/quarterly GST filings.',
    when: 'By December 31st of the following financial year.',
    where: 'GST Portal',
    whereUrl: 'https://www.gst.gov.in/',
    how: 'Consolidate GSTR-1 and GSTR-3B data and file via GSTR-9.',
    penalty: '₹200 per day of delay.',
    isMandatory: true,
    trigger: (inputs) => inputs.turnover !== 'Pre-revenue',
  },
  {
    id: 'gst-reconciliation',
    category: 'Taxation',
    name: 'GST Reconciliation (GSTR-9C)',
    urgency: 'Yellow',
    what: 'Reconciliation statement between GSTR-9 and audited financial statements.',
    when: 'By December 31st for entities with turnover > ₹5Cr.',
    where: 'GST Portal',
    whereUrl: 'https://www.gst.gov.in/',
    how: 'Self-certified reconciliation statement filed via GSTR-9C.',
    penalty: 'General penalty of ₹25,000.',
    isMandatory: true,
    trigger: (inputs) => ['₹5Cr - ₹100Cr', '> ₹100Cr'].includes(inputs.turnover),
  },
  {
    id: 'e-invoicing-gst',
    category: 'Taxation',
    name: 'E-Invoicing Compliance',
    urgency: 'Red',
    what: 'Mandatory generation of Invoice Reference Number (IRN) for B2B invoices.',
    when: 'Real-time for entities with turnover > ₹5Cr.',
    where: 'Invoice Registration Portal (IRP)',
    whereUrl: 'https://einvoice1.gst.gov.in/',
    how: 'Generate JSON of invoice and upload to IRP to get IRN and QR code.',
    penalty: '100% of tax due or ₹10,000 (per invoice).',
    isMandatory: true,
    trigger: (inputs) => ['₹5Cr - ₹100Cr', '> ₹100Cr'].includes(inputs.turnover),
  },

  // --- LABOR LAW PILLAR ---
  {
    id: 'shop-act',
    category: 'Labor Law',
    name: 'Shop & Establishment License',
    urgency: 'Yellow',
    what: 'Basic registration for any commercial establishment under state law.',
    when: 'Within 30 days of starting operations.',
    where: 'State Labor Dept Portal',
    whereUrl: 'https://lms.mahaonline.gov.in/',
    how: 'Apply online with business details, owner ID, and address proof.',
    penalty: 'Varies by state (₹1,000 to ₹10,000).',
    isMandatory: true,
    trigger: (inputs) => true,
  },
  {
    id: 'prof-tax',
    category: 'Labor Law',
    name: 'Professional Tax (PT) Registration',
    urgency: 'Yellow',
    what: 'State-level tax on professions, trades, and employments.',
    when: 'Within 30 days of starting operations (PTEC) or hiring (PTRC).',
    where: 'State Commercial Tax Portal',
    whereUrl: 'https://www.mahagst.gov.in/',
    how: 'Obtain PTRC (Employer) and PTEC (Entity) registrations.',
    penalty: '₹1,000 - ₹5,000 flat fine + interest.',
    isMandatory: true,
    trigger: (inputs) => {
      const ptStates = [
        'Andhra Pradesh', 'Assam', 'Bihar', 'Gujarat', 'Jharkhand', 'Karnataka', 'Kerala', 
        'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland', 
        'Odisha', 'Sikkim', 'Tamil Nadu', 'Telangana', 'Tripura', 'West Bengal'
      ];
      return ptStates.includes(inputs.state);
    },
  },
  {
    id: 'epf-reg',
    category: 'Labor Law',
    name: 'EPF Registration',
    urgency: 'Yellow',
    what: 'Employee Provident Fund registration for social security.',
    when: 'Mandatory when headcount reaches 20 employees.',
    where: 'EPFO Portal',
    whereUrl: 'https://www.epfindia.gov.in/',
    how: 'Register establishment and obtain Establishment ID.',
    penalty: 'Heavy interest + potential imprisonment.',
    isMandatory: true,
    trigger: (inputs) => inputs.headcount >= 20,
  },
  {
    id: 'esi-reg',
    category: 'Labor Law',
    name: 'ESI Registration',
    urgency: 'Yellow',
    what: 'Employee State Insurance for health and medical benefits.',
    when: 'Mandatory when headcount reaches 10 employees.',
    where: 'ESIC Portal',
    whereUrl: 'https://www.esic.gov.in/',
    how: 'Register establishment and generate Pehchan cards for staff.',
    penalty: 'Interest + Penalties on unpaid contributions.',
    isMandatory: true,
    trigger: (inputs) => inputs.headcount >= 10,
  },
  {
    id: 'posh-act',
    category: 'Labor Law',
    name: 'POSH Act Compliance',
    urgency: 'Red',
    what: 'Prevention of Sexual Harassment at Workplace compliance.',
    when: 'Mandatory for every entity with 10 or more employees.',
    where: 'Internal / District Officer',
    whereUrl: 'https://wcd.nic.in/',
    how: 'Form an Internal Committee (IC), draft policy, and conduct annual training.',
    penalty: '₹50,000 + potential cancellation of business license.',
    isMandatory: true,
    trigger: (inputs) => inputs.headcount >= 10,
  },
  {
    id: 'gratuity-act',
    category: 'Labor Law',
    name: 'Payment of Gratuity',
    urgency: 'Yellow',
    what: 'Statutory benefit for employees completing 5 years of service.',
    when: 'Mandatory for entities with 10 or more employees.',
    where: 'Internal / LIC Gratuity Fund',
    whereUrl: 'https://www.licindia.in/',
    how: 'Obtain Gratuity Insurance or maintain a separate gratuity fund.',
    penalty: 'Imprisonment up to 2 years for non-payment.',
    isMandatory: true,
    trigger: (inputs) => inputs.headcount >= 10,
  },
  {
    id: 'lwf-compliance',
    category: 'Labor Law',
    name: 'Labour Welfare Fund (LWF)',
    urgency: 'Yellow',
    what: 'State-specific fund for employee welfare activities.',
    when: 'Half-yearly or Annual contributions.',
    where: 'State Labor Welfare Board',
    whereUrl: 'https://public.mlwb.in/',
    how: 'Deduct employee share and add employer share; deposit via portal.',
    penalty: 'Interest + Penalties varying by state.',
    isMandatory: true,
    trigger: (inputs) => {
      const lwfStates = [
        'Andhra Pradesh', 'Chandigarh', 'Chhattisgarh', 'Delhi', 'Goa', 'Gujarat', 'Haryana', 
        'Karnataka', 'Kerala', 'Madhya Pradesh', 'Maharashtra', 'Odisha', 'Punjab', 
        'Tamil Nadu', 'Telangana', 'West Bengal'
      ];
      return inputs.headcount > 0 && lwfStates.includes(inputs.state);
    },
  },
  {
    id: 'privacy-policy',
    category: 'Legal',
    name: 'Privacy Policy & Terms of Service',
    urgency: 'Red',
    what: 'Legal documents governing user interaction and data handling.',
    when: 'Mandatory before launching any digital product/website.',
    where: 'Website / App Footer',
    whereUrl: 'https://www.meity.gov.in/',
    how: 'Draft policies compliant with IT Act and DPDP Act; display prominently.',
    penalty: 'Legal liability + Potential fines under DPDP Act.',
    isMandatory: true,
    trigger: (inputs) => inputs.dataProcessing === true || inputs.isEcommerce === true,
  },
  {
    id: 'copyright-reg',
    category: 'Incentives',
    name: 'Copyright Registration',
    urgency: 'Incentive',
    what: 'Protecting original creative works (code, content, designs).',
    when: 'Recommended for software and creative startups.',
    where: 'Copyright Office',
    whereUrl: 'https://copyright.gov.in/',
    how: 'File Form XIV with the work sample and fees.',
    penalty: 'N/A (Optional), but risks content theft.',
    isMandatory: false,
    trigger: (inputs) => true,
  },
  {
    id: 'patent-filing',
    category: 'Incentives',
    name: 'Patent Filing',
    urgency: 'Incentive',
    what: 'Protecting novel inventions or processes.',
    when: 'Before public disclosure of the invention.',
    where: 'IP India Portal',
    whereUrl: 'https://ipindiaonline.gov.in/',
    how: 'File provisional or complete specification with technical details.',
    penalty: 'N/A (Optional), but risks losing IP rights.',
    isMandatory: false,
    trigger: (inputs) => inputs.industry === 'Manufacturing' || inputs.businessModel === 'Product',
  },

  // --- GROWTH & INCENTIVES (OPTIONAL) ---
  {
    id: 'startup-india',
    category: 'Incentives',
    name: 'DPIIT Startup Recognition',
    urgency: 'Incentive',
    what: 'Official recognition as a "Startup" to unlock tax and IP benefits.',
    when: 'Anytime after incorporation (valid for 10 years).',
    where: 'Startup India Portal',
    whereUrl: 'https://www.startupindia.gov.in/',
    how: 'Apply with a write-up on innovation, scalability, and business model.',
    penalty: 'N/A (Optional), but unlocks 80-IAC and angel tax benefits.',
    isMandatory: false,
    trigger: (inputs) => !inputs.isDPIITRecognized && ['Pvt Ltd', 'LLP'].includes(inputs.entityType),
  },
  {
    id: 'udyam-reg',
    category: 'Incentives',
    name: 'Udyam (MSME) Registration',
    urgency: 'Incentive',
    what: 'Registration to avail benefits like priority lending and MSME payment protection.',
    when: 'Voluntary, recommended for all startups.',
    where: 'Udyam Portal',
    whereUrl: 'https://udyamregistration.gov.in/',
    how: 'Register using Aadhaar and PAN of the promoter.',
    penalty: 'N/A (Optional), but enables Sec 43B(h) protection.',
    isMandatory: false,
    trigger: (inputs) => true,
  },
  {
    id: 'trademark-reg',
    category: 'Incentives',
    name: 'Trademark Registration',
    urgency: 'Incentive',
    what: 'Protecting your brand name and logo.',
    when: 'Recommended at the start of operations.',
    where: 'IP India Portal',
    whereUrl: 'https://ipindiaonline.gov.in/',
    how: 'File TM-A with brand details and user affidavit.',
    penalty: 'N/A (Optional), but risks brand infringement.',
    isMandatory: false,
    trigger: (inputs) => true,
  },
  {
    id: 'iec-code',
    category: 'Conditional',
    name: 'Import Export Code (IEC)',
    urgency: 'Yellow',
    what: 'Mandatory license for importing or exporting goods/services.',
    when: 'Before starting any cross-border trade.',
    where: 'DGFT Portal',
    whereUrl: 'https://www.dgft.gov.in/',
    how: 'Apply online with PAN and bank details.',
    penalty: 'Cannot clear customs without IEC.',
    isMandatory: true,
    trigger: (inputs) => inputs.foreignInvestment === true || inputs.isEcommerce === true,
  },
  {
    id: 'maternity-benefit',
    category: 'Labor Law',
    name: 'Maternity Benefit Act',
    urgency: 'Red',
    what: 'Mandatory paid leave and benefits for female employees.',
    when: 'Mandatory for every entity with 10 or more employees.',
    where: 'Internal / Labor Dept',
    whereUrl: 'https://labour.gov.in/',
    how: 'Provide 26 weeks of paid leave and maintain registers.',
    penalty: 'Imprisonment up to 1 year + Fine.',
    isMandatory: true,
    trigger: (inputs) => inputs.headcount >= 10,
  },
  {
    id: 'bonus-act',
    category: 'Labor Law',
    name: 'Payment of Bonus Act',
    urgency: 'Yellow',
    what: 'Mandatory annual bonus to employees earning below a certain threshold.',
    when: 'Within 8 months of the close of the financial year.',
    where: 'Internal / Labor Dept',
    whereUrl: 'https://labour.gov.in/',
    how: 'Calculate bonus (8.33% to 20%) and distribute to eligible staff.',
    penalty: 'Fine and potential imprisonment.',
    isMandatory: true,
    trigger: (inputs) => inputs.headcount >= 20,
  },
  {
    id: 'clra-reg',
    category: 'Labor Law',
    name: 'Contract Labour (CLRA) Registration',
    urgency: 'Yellow',
    what: 'Registration for principal employers engaging contract labor.',
    when: 'Before engaging contract labor exceeding 20/50 persons.',
    where: 'State Labor Dept',
    whereUrl: 'https://shramsuvidha.gov.in/',
    how: 'Apply for registration as Principal Employer.',
    penalty: 'Fine and potential cancellation of license.',
    isMandatory: true,
    trigger: (inputs) => inputs.hasContractLabor === true,
  },
  {
    id: 'posh-annual-report',
    category: 'Labor Law',
    name: 'POSH Annual Compliance Report',
    urgency: 'Green',
    what: 'Annual report summarizing sexual harassment complaints and actions.',
    when: 'By January 31st every year for the previous calendar year.',
    where: 'District Officer (Local Authority)',
    whereUrl: 'https://wcd.nic.in/',
    how: 'Submit a physical or online report to the District Officer.',
    penalty: '₹50,000 for non-filing.',
    isMandatory: true,
    trigger: (inputs) => inputs.headcount >= 10,
  },
  {
    id: 'tcs-compliance',
    category: 'Taxation',
    name: 'TCS Compliance (Sec 52/206C)',
    urgency: 'Yellow',
    what: 'Collection of tax at source on specific transactions or e-commerce sales.',
    when: 'Monthly deposit by 7th of next month.',
    where: 'Income Tax / GST Portal',
    whereUrl: 'https://www.gst.gov.in/',
    how: 'Collect tax from buyers/sellers and deposit with the government.',
    penalty: 'Interest + Penalty equal to tax amount.',
    isMandatory: true,
    trigger: (inputs) => inputs.isEcommerce === true || inputs.turnover === '> ₹100Cr',
  },
  {
    id: 'fssai-reg',
    category: 'Industry Specific',
    name: 'FSSAI License / Registration',
    urgency: 'Red',
    what: 'Food safety license for any business involved in food handling.',
    when: 'Before starting food-related operations.',
    where: 'FoSCoS Portal',
    whereUrl: 'https://foscos.fssai.gov.in/',
    how: 'Apply for Registration, State License, or Central License based on capacity.',
    penalty: 'Up to ₹5 Lakh + Imprisonment.',
    isMandatory: true,
    trigger: (inputs) => inputs.industry === 'Food & Agri',
  },
  {
    id: 'pcb-consent',
    category: 'Industry Specific',
    name: 'Pollution Board Consent (CTE/CTO)',
    urgency: 'Red',
    what: 'Environmental clearance for manufacturing or polluting activities.',
    when: 'Consent to Establish (CTE) before setup; Consent to Operate (CTO) before start.',
    where: 'State Pollution Control Board',
    whereUrl: 'https://cpcb.nic.in/',
    how: 'Apply online with project report and pollution control measures.',
    penalty: 'Closure of unit + Heavy environmental compensation.',
    isMandatory: true,
    trigger: (inputs) => inputs.industry === 'Manufacturing',
  },
  {
    id: 'ecb-reporting',
    category: 'FEMA / RBI',
    name: 'ECB Reporting (Form ECB)',
    urgency: 'Red',
    what: 'Reporting of External Commercial Borrowings (foreign loans).',
    when: 'Monthly reporting via Form ECB-2.',
    where: 'RBI FIRMS / AD Bank',
    whereUrl: 'https://firms.rbi.org.in/',
    how: 'Obtain LRN from RBI and file monthly returns through AD Bank.',
    penalty: 'Heavy compounding fees.',
    isMandatory: true,
    trigger: (inputs) => inputs.hasForeignLoans === true,
  },
  {
    id: 'transfer-pricing',
    category: 'Taxation',
    name: 'Transfer Pricing Audit (Form 3CEB)',
    urgency: 'Red',
    what: 'Audit of international transactions with associated enterprises.',
    when: 'By October 31st annually.',
    where: 'Income Tax Portal',
    whereUrl: 'https://www.incometax.gov.in/',
    how: 'Appoint a CA to audit international transactions and file Form 3CEB.',
    penalty: '2% of transaction value.',
    isMandatory: true,
    trigger: (inputs) => inputs.foreignInvestment === true && inputs.turnover !== 'Pre-revenue',
  },
  {
    id: 'fc-gpr',
    category: 'FEMA / RBI',
    name: 'FC-GPR Filing',
    urgency: 'Red',
    what: 'Reporting FDI to the Reserve Bank of India.',
    when: 'Within 30 days of share allotment.',
    where: 'RBI FIRMS Portal',
    whereUrl: 'https://firms.rbi.org.in/',
    how: 'Submit Form FC-GPR with CS certificate and Valuation report.',
    penalty: 'Heavy compounding fees (Lakhs).',
    isMandatory: true,
    trigger: (inputs) => inputs.foreignInvestment === true,
  },
  {
    id: 'fla-return',
    category: 'FEMA / RBI',
    name: 'FLA Return',
    urgency: 'Yellow',
    what: 'Annual Return on Foreign Liabilities and Assets.',
    when: 'By July 15th every year.',
    where: 'RBI FLAIR Portal',
    whereUrl: 'https://flair.rbi.org.in/',
    how: 'File details of FDI and ODI based on audited financials.',
    penalty: '₹5,000 to ₹10,000 per month of delay.',
    isMandatory: true,
    trigger: (inputs) => inputs.foreignInvestment === true,
  },
  {
    id: 'fc-trs',
    category: 'FEMA / RBI',
    name: 'Share Transfer Reporting (FC-TRS)',
    urgency: 'Conditional',
    what: 'Reporting transfer of shares between a resident and a non-resident.',
    when: 'Within 60 days of transfer of funds or shares.',
    where: 'RBI FIRMS Portal',
    whereUrl: 'https://firms.rbi.org.in/',
    how: 'File Form FC-TRS online with share transfer deed and valuation report.',
    penalty: 'Heavy compounding fees (Lakhs).',
    isMandatory: true,
    trigger: (inputs) => inputs.foreignInvestment === true,
  },
  {
    id: 'odi-reporting',
    category: 'FEMA / RBI',
    name: 'Overseas Direct Investment (ODI)',
    urgency: 'Red',
    what: 'Reporting of investment made by the Indian entity in a foreign entity.',
    when: 'Within 30 days of investment.',
    where: 'RBI FIRMS Portal',
    whereUrl: 'https://firms.rbi.org.in/',
    how: 'File Form ODI through an Authorized Dealer (AD) Bank.',
    penalty: 'Compounding fees and potential restriction on further remittances.',
    isMandatory: true,
    trigger: (inputs) => inputs.foreignInvestment === true,
  },

  // --- DATA PRIVACY ---
  {
    id: 'dpdp-act',
    category: 'Data Privacy',
    name: 'DPDP Act Compliance',
    urgency: 'Red',
    what: 'Digital Personal Data Protection Act requirements for data fiduciaries.',
    when: 'Ongoing (Rules being notified in 2024-25).',
    where: 'Data Protection Board (Upcoming)',
    whereUrl: 'https://www.meity.gov.in/',
    how: 'Implement consent managers, data audit trails, and privacy notices.',
    penalty: 'Up to ₹250 Crores for significant breaches.',
    isMandatory: true,
    trigger: (inputs) => inputs.dataProcessing === true,
  },
];
